version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/nestjs
    networks:
      - nestjs-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
